applications:
  index_fields:
    Id:
    Name:
      label: 'Application Number'
    Listing__r.Name:
      label: 'Listing Name'
    Listing__r.Lottery_Date__c:
      label: 'Lottery Date'
    Applicant__r.First_Name__c:
    Applicant__r.Last_Name__c:
    Application_Submitted_Date__c:
      type: 'date'
    Total_Household_Size__c:
    Application_Submission_Type__c:
      # TBD: can remove these once we remove spreadsheet view
      editable: true
      editable_options:
        - Electronic
        - Paper
  show_preference_fields:
    Id:
    Name:
    Preference_Name__c:
    Person_who_claimed_Name__c:
    Type_of_proof__c:
    Opt_Out__c:
    Lottery_Status__c:
      label: 'Pre-lottery Validation'
    Preference_Lottery_Rank__c:
      label: 'Lottery Rank'
    Listing_Preference_ID__c:
    Receives_Preference__c:
    Application_Member__c:
    Application_Member__r.First_Name__c:
    Application_Member__r.Last_Name__c:
    Application_Member__r.Date_of_Birth__c:
    Application_Member__r.Id:
    Individual_preference__c:
    Certificate_Number__c:
    Preference_Order__c:
    RecordType.DeveloperName:
    LW_Type_of_Proof__c:
    City__c:
    State__c:
    Street__c:
    Zip_Code__c:
    Post_Lottery_Validation__c:
  show_flagged_records_fields:
    Flagged_Record_Set__c:
    Flagged_Record_Set__r.Id:
    Flagged_Record_Set__r.Rule_Name__c:
      label: 'Flagged Fields'
    Flagged_Record_Set__r.Total_Number_of_Pending_Review__c:
      label: 'Applications Pending Review'
  show_proof_files_fields:
    Id:
    Name:
  show_household_members_fields:
    Id:
    Name__c:
    First_Name__c:
    Last_Name__c:
    Middle_Name__c:
    Relationship_to_Applicant__c:
    Date_of_Birth__c:
    Street__c:
    City__c:
    State__c:
    Zip_Code__c :
  show_fields:
    Id:
    Name:
      label: 'Application Number'
    Applicant__c:
    Alternate_Contact__c:
    Listing__c:
    Listing__r.Name:
      label: 'Listing Name'
    Listing__r.Id:
    Status__c:
    Listing__r.Reserved_community_type__c:
    Total_Household_Size__c:
    Application_Submission_Type__c:
    Application_Submitted_Date__c:
    CreatedBy.Name:
      label: 'Created By'
    Annual_Income__c:
    Monthly_Income__c:
    Is_Lottery_Complete__c:
    Housing_Voucher_or_Subsidy__c:
    Referral_Source__c:
    Application_Language__c:
    Lottery_Number_Manual__c:
    Lottery_Number__c:
    Total_Monthly_Rent__c:
    General_Lottery__c:
    General_Lottery_Rank__c:
    Answered_Community_Screening__c:
    Has_Military_Service__c:
    Reserved_Senior__c:
    Has_DevelopmentalDisability__c:
        label: 'Has Developmental Disability'
    Has_ADA_Priorities_Selected__c:
    Terms_Acknowledged__c:
    Applicant__r.Id:
    Applicant__r.First_Name__c:
    Applicant__r.Last_Name__c:
    Applicant__r.Middle_Name__c:
    Applicant__r.Name__c:
    Applicant__r.Date_of_Birth__c:
    Applicant__r.Phone_Type__c:
    Applicant__r.Phone__c:
    Applicant__r.Second_Phone_Type__c:
    Applicant__r.Second_Phone__c:
    Applicant__r.Email__c:
    Applicant__r.Primary_Language__c:
    Applicant__r.Residence_Address__c:
    Applicant__r.Street__c:
    Applicant__r.City__c:
    Applicant__r.State__c:
    Applicant__r.Zip_Code__c:
    Applicant__r.Mailing_Address__c:
    Applicant__r.Mailing_Street__c:
    Applicant__r.Mailing_City__c:
    Applicant__r.Mailing_State__c:
    Applicant__r.Mailing_Zip_Code__c:
    Applicant__r.Marital_Status__c:
    Alternate_Contact__r.Id:
    Alternate_Contact__r.First_Name__c:
    Alternate_Contact__r.Middle_Name__c:
    Alternate_Contact__r.Last_Name__c:
    Alternate_Contact__r.Phone_Type__c:
    Alternate_Contact__r.Phone__c:
    Alternate_Contact__r.Email__c:
    Alternate_Contact__r.Agency_Name__c:
    Alternate_Contact__r.Alternate_Contact_Type__c:
      label: 'Relationship'
    Alternate_Contact__r.Alternate_Contact_Type_Other__c:
      label: 'Relationship - Other'
    Number_of_Dependents__c:
