listings:
  index_fields:
    Id:
    Name:
      label: 'Listing Name'
      minWidth: 225
    Application_Due_Date__c:
      type: 'date'
    Lottery_Date__c:
      type: 'date'
    Lottery_Results_Date__c:
      type: 'date'
    Lottery_Status__c:
    nFlagged_Applications__c:
      label: 'Flagged Applications'
    In_Lottery__c:
      label: 'Applications In Lottery'
  # detail_fields copied from:
  # https://github.com/Exygy/sf-dahlia-salesforce/blob/master/src/classes/HOP_ListingController.cls
  show_fields:
    Id:
    OwnerId:
    Owner.Name:
    Application_Due_Date__c:
    Name:
    Status__c:
    Building__c:
    Building__r.Name:
      label: 'Building'
    Building_Name_for_Process__c:
      label: 'Building Name for Process'
    Min_BR__c:
    Lottery_Winners__c:
    Max_BR__c:
    Lottery_Results__c:
    Min_Income__c:
    Account__c:
    Account__r.Name:
    Max_Income__c:
    Min_Occupancy__c:
    Max_Occupancy__c:
    Building_Name__c:
    Neighborhood__c:
    Building_Street_Address__c:
    Developer__c:
    Building_City__c:
    Building_URL__c:
    Building_State__c:
    Year_Built__c:
    Building_Zip_Code__c:
    Description__c:
    Lottery_Preferences__c:
    Accessibility__c:
    Fee__c:
    Amenities__c:
    Deposit_Min__c:
    Costs_Not_Included__c:
    Deposit_Max__c:
    Lottery_Date__c:
    Lottery_Results_Date__c:
    Lottery_Venue__c:
    Lottery_Summary__c:
    Lottery_Street_Address__c:
    Lottery_City__c:
    Lottery_URL__c:
    Reserved_community_type__c:
    # ------------------
    Application_Phone__c:
    Application_Organization__c:
    Application_Street_Address__c:
    Application_City__c:
    Download_URL__c:
    Application_State__c:
    Application_Postal_Code__c:
    In_Lottery__c:
      label: 'Applications in Lottery'
    Leasing_Agent_Name__c:
    Leasing_Agent_Title__c:
    Leasing_Agent_Email__c:
    Leasing_Agent_Phone__c:
    Legal_Disclaimers__c:
    Building_Selection_Criteria__c:
    Pet_Policy__c:
    Report_id__c:
    Required_Documents__c:
    Smoking_Policy__c:
    Eviction_History__c:
    Criminal_History__c:
    Credit_Rating__c:
    Lottery_Status__c:
    Office_Hours__c:
    Tenure__c:
    Listing_Type__c:
    File_Upload_URL__c:
    Program_Type__c:
  lease_up_listing_fields:
    Id:
    Name:
    Lottery_Date__c:
    Lottery_Results_Date__c:
    In_Lottery__c:
    Units_Available__c:
    Lease_Signed_Application__c:
    LastModifiedDate:
