preferences:
  app_preferences_for_application_fields:
    Id:
    Name:
    Preference_Name__c:
    Person_who_claimed_Name__c:
    Type_of_proof__c:
    Veteran_Type_of_Proof__c:
    Opt_Out__c:
    Lottery_Status__c:
      label: "Pre-lottery Validation"
    Preference_Lottery_Rank__c:
      label: "Lottery Rank"
    Listing_Preference_ID__c:
    Receives_Preference__c:
    Application_Member__c:
    Application_Member__r.First_Name__c:
    Application_Member__r.Last_Name__c:
    Application_Member__r.Date_of_Birth__c:
    Application_Member__r.Id:
    Individual_preference__c:
    Certificate_Number__c:
    Preference_Order__c:
    RecordType.DeveloperName:
    LW_Type_of_Proof__c:
    City__c:
    State__c:
    Street__c:
    Zip_Code__c:
    Post_Lottery_Validation__c:
    Lottery_Status__c:
    Total_Household_Rent__c:
    Custom_Preference_Type__c:
  app_preferences_for_listing_fields:
    Application__c:
    Application__r.Name:
    Listing_ID__c:
    Application__r.Id:
    Application__r.General_Lottery__c:
    Application__r.General_Lottery_Rank__c:
    Application__r.Applicant__r.First_Name__c:
    Application__r.Applicant__r.Last_Name__c:
    Application__r.Applicant__r.Residence_Address__c:
    Application__r.Applicant__r.Mailing_Address__c:
    Application__r.Has_ADA_Priorities_Selected__c:
    Application__r.Total_Household_Size__c:
    Preference_Order__c:
    Receives_Preference__c:
    Preference_All_Name__c:
    Preference_All_Lottery_Rank__c:
    Post_Lottery_Validation__c:
    Lottery_Status__c:
    Preference_Lottery_Rank__c:
    Receives_Preference__c:
    Application__r.Sub_Status__c:
    Application__r.Processing_Status__c:
      label: "Lease Up Status"
    Application__r.Processing_Date_Updated__c:
      label: "Status Updated"
    Listing_Preference_ID__r.Record_Type_For_App_Preferences__c:
    Custom_Preference_Type__c:
    Layered_Preference_Validation__c:
  app_preferences_for_lottery_results_fields:
    Application__r.General_Lottery__c:
    Application__r.General_Lottery_Rank__c:
    Application__r.Lottery_Number__c:
    Application__r.Lottery_Number_Manual__c:
    Application__r.Lottery_Rank__c:
    Preference_All_Name__c:
    Preference_Lottery_Rank__c:
    Listing_Preference_ID__r.Record_Type_For_App_Preferences__c:
    Custom_Preference_Type__c:
