listings:
  index_fields:
    Id:
    Name:
      label: 'Listing Name'
      minWidth: 225
    Application_Due_Date__c:
      type: 'date'
    Lottery_Date__c:
      type: 'date'
    Lottery_Results_Date__c:
      type: 'date'
    Lottery_Status__c:
    nFlagged_Applications__c:
      label: 'Flagged Applications'
    In_Lottery__c:
      label: 'Applications In Lottery'
  # detail_fields copied from:
  # https://github.com/Exygy/sf-dahlia-salesforce/blob/master/src/classes/HOP_ListingController.cls
  show_fields:
    Id:
    OwnerId:
    Owner.Name:
    Application_Due_Date__c:
    Name:
    Status__c:
    Building__c:
    Building__r.Name:
      label: 'Building'
    Min_BR__c:
    Lottery_Winners__c:
    Max_BR__c:
    Lottery_Results__c:
    Min_Income__c:
    Account__c:
    Account__r.Name:
    Max_Income__c:
    Min_Occupancy__c:
    Max_Occupancy__c:
    Building_Name__c:
    Neighborhood__c:
    Building_Street_Address__c:
    Developer__c:
    Building_City__c:
    Building_URL__c:
    Building_State__c:
    Year_Built__c:
    Building_Zip_Code__c:
    Description__c:
    Lottery_Preferences__c:
    Accessibility__c:
    Fee__c:
    Amenities__c:
    Deposit_Min__c:
    Costs_Not_Included__c:
    Deposit_Max__c:
    Lottery_Date__c:
    Lottery_Results_Date__c:
    Lottery_Venue__c:
    Lottery_Summary__c:
    Lottery_Street_Address__c:
    Lottery_City__c:
    Lottery_URL__c:
    Reserved_community_type__c:
    # ------------------
    Application_Phone__c:
    Application_Organization__c:
    Application_Street_Address__c:
    Application_City__c:
    Download_URL__c:
    Application_State__c:
    Organization_URL__c:
    Application_Postal_Code__c:
    In_Lottery__c:
      label: 'Applications in Lottery'
    Leasing_Agent_Name__c:
    Leasing_Agent_Title__c:
    Leasing_Agent_Email__c:
    Leasing_Agent_Phone__c:
    Legal_Disclaimers__c:
    Building_Selection_Criteria__c:
    Pet_Policy__c:
    Required_Documents__c:
    Smoking_Policy__c:
    Eviction_History__c:
    Criminal_History__c:
    Credit_Rating__c:
    Lottery_Status__c:
    Office_Hours__c:

applications:
  index_fields:
    Id:
    Name:
      label: 'Application Number'
    Listing__r.Name:
      label: 'Listing Name'
    Listing__r.Lottery_Date__c:
      label: 'Lottery Date'
    Applicant__r.First_Name__c:
    Applicant__r.Last_Name__c:
    Application_Submitted_Date__c:
      type: 'date'
    Total_Household_Size__c:
    Application_Submission_Type__c:
      # TBD: can remove these once we remove spreadsheet view
      editable: true
      editable_options:
        - Electronic
        - Paper
  show_preference_fields:
    Id:
    Name:
    Preference_Name__c:
    Person_who_claimed_Name__c:
    Type_of_proof__c:
    Opt_Out__c:
    Lottery_Status__c:
      label: 'Pre-lottery Validation'
    Preference_Lottery_Rank__c:
      label: 'Lottery Rank'
    Listing_Preference_ID__c:
    Receives_Preference__c:
    Application_Member__c:
    Application_Member__r.First_Name__c:
    Application_Member__r.Last_Name__c:
    Application_Member__r.Date_of_Birth__c:
    Individual_preference__c:
    Certificate_Number__c:
    Preference_Order__c:
  show_flagged_records_fields:
    Flagged_Record_Set__c:
    Flagged_Record_Set__r.Rule_Name__c:
      label: 'Flagged Fields'
    Flagged_Record_Set__r.Total_Number_of_Pending_Review__c:
      label: 'Applications Pending Review'
  show_proof_files_fields:
    Id:
    Name:
  show_household_members_fields:
    Id:
    Name__c:
    First_Name__c:
    Last_Name__c:
    Middle_Name__c:
    Relationship_to_Applicant__c:
    Date_of_Birth__c:
    Street__c:
    City__c:
    State__c:
    Zip_Code__c :
  show_fields:
    Id:
    Name:
      label: 'Application Number'
    Applicant__c:
    Alternate_Contact__c:
    Listing__c:
    Listing__r.Name:
      label: 'Listing Name'
    Listing__r.Id:
    Status__c:
    Listing__r.Reserved_community_type__c:
    Total_Household_Size__c:
    Application_Submission_Type__c:
    Application_Submitted_Date__c:
    CreatedBy.Name:
      label: 'Created By'
    Annual_Income__c:
    Monthly_Income__c:
    Is_Lottery_Complete__c:
    Housing_Voucher_or_Subsidy__c:
    Referral_Source__c:
    Application_Language__c:
    Lottery_Number_Manual__c:
    Lottery_Number__c:
    Total_Monthly_Rent__c:
    General_Lottery__c:
    General_Lottery_Rank__c:
    Answered_Community_Screening__c:
    Has_Military_Service__c:
    Has_DevelopmentalDisability__c:
        label: 'Has Developmental Disability'
    Has_ADA_Priorities_Selected__c:
    Terms_Acknowledged__c:
    Applicant__r.Id:
    Applicant__r.First_Name__c:
    Applicant__r.Last_Name__c:
    Applicant__r.Middle_Name__c:
    Applicant__r.Name__c:
    Applicant__r.Date_of_Birth__c:
    Applicant__r.Phone_Type__c:
    Applicant__r.Phone__c:
    Applicant__r.Second_Phone_Type__c:
    Applicant__r.Second_Phone__c:
    Applicant__r.Email__c:
    Applicant__r.Primary_Language__c:
    Applicant__r.Residence_Address__c:
    Applicant__r.Street__c:
    Applicant__r.City__c:
    Applicant__r.State__c:
    Applicant__r.Zip_Code__c:
    Applicant__r.Mailing_Address__c:
    Applicant__r.Mailing_Street__c:
    Applicant__r.Mailing_City__c:
    Applicant__r.Mailing_State__c:
    Applicant__r.Mailing_Zip_Code__c:
    Alternate_Contact__r.Id:
    Alternate_Contact__r.First_Name__c:
    Alternate_Contact__r.Middle_Name__c:
    Alternate_Contact__r.Last_Name__c:
    Alternate_Contact__r.Phone_Type__c:
    Alternate_Contact__r.Phone__c:
    Alternate_Contact__r.Email__c:
    Alternate_Contact__r.Agency_Name__c:
    Alternate_Contact__r.Alternate_Contact_Type__c:
      label: 'Relationship'
    Alternate_Contact__r.Alternate_Contact_Type_Other__c:
      label: 'Relationship - Other'

flagged_record_sets:
  pending_review_fields:
    Id:
    Listing__r.Name:
      label: 'Listing Name'
    Rule_Name__c:
    Total_Number_of_Pending_Review__c:
    Total_Number_of_Appealed__c:
  marked_duplicate_fields:
    Id:
    Listing__r.Name:
      label: 'Listing Name'
    Rule_Name__c:
    Total_Number_of_Duplicates__c:
  flagged_applications_fields:
    Id:
    Application__c:
    Application__r.Name:
      label: 'App Number'
    Flagged_Record_Set__r.Rule_Name__c:
    Primary_Application_Applicant_Name__c:
      label: 'Primary Applicant Name'
    Flagged_Record_Set__r.Listing__r.Lottery_Status__c:
      label: 'Lottery Status'
    Review_Status__c:
      editable: true
      editable_options:
        - Pending Review
        - Reviewed - Keep in Lottery
        - Reviewed - Remove from Lottery
        - Appealed
    Comments__c:
      editable: true
